
name: QA Practice

on: push

jobs:
  qa-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check calculator result
        run: |
          python -c "assert 2 + 3 == 6, 'Expected 5, but calculation failed'"
