name: QA Practice

on: push

jobs:
  qa-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check calculator result
        run: |
          python -c "assert 2 + 3 == 5, 'Expected 5, but calculation failed'"

      - name: Check subtraction
        run: |
          python -c "assert 10 - 4 == 6, 'Expected 6, but subtraction failed'"

      - name: Check multiplication
        run: |
          python -c "assert 5 * 5 == 25, 'Expected 25, but multiplication failed'"
